
#ifndef _LANGUAGE_EN_S_H_
#define _LANGUAGE_EN_S_H_

#define S_SETTING_WIFI_SSID                                    "Setting WIFI"
#define S_WIFI_SSID                                            "Name WIFI"
#define S_WIFI_PASS                                            "Password"
#define S_HOST_NAME                                            "Module name"
#define S_SETTING_SUPLA                                        "Settings SUPLA"
#define S_SUPLA_SERVER                                         "Server address"
#define S_SUPLA_EMAIL                                          "Email"
#define S_SETTING_ADMIN                                        "Administrator settings"
#define S_LOGIN                                                "Login"
#define S_LOGIN_PASS                                           "Password"
#define S_ROLLERSHUTTERS                                       "Roller shuter"
#define S_SAVE                                                 "Save"
#define S_DEVICE_SETTINGS                                      "Device settings"
#define S_UPDATE                                               "Update"
#define S_RESTART                                              "Restart"
#define S_RETURN                                               "Return"
#define S_TEMPLATE_BOARD                                       "Template board"
#define S_TYPE                                                 "Type"
#define S_RELAYS                                               "RELAYS"
#define S_BUTTONS                                              "BUTTONS"
#define S_SENSORS_1WIRE                                        "SENSORS 1Wire"
#define S_SENSORS_I2C                                          "SENSORS i2c"
#define S_SENSORS_SPI                                          "SENSORS SPI"
#define S_LED_BUTTON_CFG                                       "LED, BUTTON CONFIG"
#define S_QUANTITY                                             "QUANTITY"
#define S_GPIO_SETTINGS_FOR_RELAYS                             "GPIO settings for relays"
#define S_RELAY                                                "RELAYS"
#define S_RELAY_NR_SETTINGS                                    "Settings relay no. "
#define S_NO_RELAY_NR                                          "Missing relay no."
#define S_STATE_CONTROL                                        "State control"
#define S_REACTION_AFTER_RESET                                 "Reaction after reset"
#define S_GPIO_SETTINGS_FOR_BUTTONS                            "GPIO settings for buttons"
#define S_BUTTON                                               "BUTTON"
#define S_BUTTON_NR_SETTINGS                                   "Setting button no"
#define S_NO_BUTTON_NR                                         "Missing button no."
#define S_REACTION_TO                                          "Reaction to"
#define S_GPIO_SETTINGS_FOR_LIMIT_SWITCH                       "GPIO settings for limit switch"
#define S_LIMIT_SWITCH                                         "LIMIT SWITCH"
#define S_GPIO_SETTINGS_FOR                                    "GPIO settigs for"
#define S_FOUND                                                "Found"
#define S_NO_SENSORS_CONNECTED                                 "No sensor conected"
#define S_SAVE_FOUND                                           "Save found"
#define S_TEMPERATURE                                          "Temperature"
#define S_NAME                                                 "Name"
#define S_ALTITUDE_ABOVE_SEA_LEVEL                             "Altitude"
#define S_GPIO_SETTINGS_FOR_CONFIG                             "GPIO settings for config"
#define S_SOFTWARE_UPDATE                                      "Software update"
#define S_DATA_SAVED                                           "Data saved"
#define S_RESTART_MODULE                                       "Restart module"
#define S_DATA_ERASED_RESTART_DEVICE                           "Data erased - restart module"
#define S_WRITE_ERROR_UNABLE_TO_READ_FILE_FS_PARTITION_MISSING "Write error - ubable to read from file FS. Partition missing"
#define S_DATA_SAVED_RESTART_MODULE                            "Data saved - restart module"
#define S_WRITE_ERROR_BAD_DATA                                 "Write error - bad data"

#endif  // _LANGUAGE_EN_S_H_